const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const EMPTY_CART = "EMPTY_CART";
const ADD_PRODUCT = "ADD_PRODUCT";
const PRODUCT_LIST = "PRODUCT_LIST";
const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
const SEARCH_PRODUCT = "SEARCH_PRODUCT";
const REGISTER_USER = "REGISTER_USER";
const LOGIN_USER = "LOGIN_USER";
const SET_USERS = "SET_USERS";
const USER_DATA = "USER_DATA";
const EDIT_USER = "EDIT_USER";
const UPDATE_USER = "UPDATE_USER";

export {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  EMPTY_CART,
  ADD_PRODUCT,
  PRODUCT_LIST,
  SET_PRODUCT_LIST,
  SEARCH_PRODUCT,
  REGISTER_USER,
  LOGIN_USER,
  SET_USERS,
  USER_DATA,
  EDIT_USER,
  UPDATE_USER,
};
